name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # PROJECT_DIR will be detected at runtime from the location of package.json
    env:
      PROJECT_DIR: '.'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect project directory (where package.json lives)
        id: detect
        run: |
          echo "Searching for package.json (maxdepth 5)..."
          found=$(find . -maxdepth 5 -name package.json | head -n 1 || true)
          if [ -z "$found" ]; then
            echo "NO_PACKAGE_JSON=true" >> $GITHUB_ENV
            echo "No package.json found in repository (within maxdepth 5)."
          else
            dir=$(dirname "$found")
            # Normalize '.' path
            if [ "$dir" = "." ]; then
              echo "PROJECT_DIR=." >> $GITHUB_ENV
            else
              # strip leading ./ if present
              dir=${dir#./}
              echo "PROJECT_DIR=$dir" >> $GITHUB_ENV
            fi
            echo "Found package.json at: $found"
            echo "PROJECT_DIR set to: $dir"
          fi
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        # Use npm ci when a lockfile exists, otherwise fall back to npm install
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          if [ -f package-lock.json ] ; then
            echo "Found package-lock.json, running npm ci"
            npm ci
          else
            echo "No package-lock.json found, running npm install to generate a lockfile"
            npm install
          fi
        shell: bash

      - name: Build
        working-directory: ${{ env.PROJECT_DIR }}
        run: npm run build

      - name: Publish to Cloudflare Pages (Wrangler)
        # Uses Wrangler to publish the `build` directory to Pages
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          echo "Publishing from project dir: ${{ env.PROJECT_DIR }}"
          npx wrangler@3 pages publish build --project-name="${{ secrets.CF_PROJECT_NAME }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        shell: bash
